spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      jdbc:
        time_zone: UTC
    show-sql: true
  flyway:
    enabled: true
    # baseline-on-migrate: true
    baseline-version: 1
  jackson:
    property-naming-strategy: SNAKE_CASE
  cache:
    type: redis
  batch:
    jdbc:
      initialize-schema: never

server:
  forward-headers-strategy: framework

siksha:
  banned:
    words:
  firebase:
    service-account:

oci:
  vault:
    secret-ids: ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqaei57kzdeagsdtu66oqxvqjreh3hort4k67tfzvvlb65q
    region: ap-chuncheon-1


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host:
      port:

oci:
  object-storage:
    namespace: ax1dvc8vmenm
    region: ap-chuncheon-1
    bucket: siksha-dev

jwt:
  secret-key:

siksha:
  oauth:
    google:
      client-id:
        android:
        ios-prod:
        ios-dev:
        web-prod:
        web-dev:
    kakao:
      app-id:
    apple:
      approved-audience:

slack:
  channel:
  token:

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host:
      port:

oci:
  object-storage:
    namespace: ax1dvc8vmenm
    region: ap-chuncheon-1
    bucket: siksha-dev

jwt:
  secret-key:

siksha:
  oauth:
    google:
      client-id:
        android:
        ios-prod:
        ios-dev:
        web-prod:
        web-dev:
    kakao:
      app-id:
    apple:
      approved-audience:

slack:
  channel:
  token:

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host:
      port:

oci:
  object-storage:
    namespace: ax1dvc8vmenm
    region: ap-chuncheon-1
    bucket: siksha
  vault:
    secret-ids: ocid1.vaultsecret.oc1.ap-chuncheon-1.amaaaaaat2m5lbqazni6mmnbxjxj5wanooaxsggjl2unxtru33hplioigtkq
    region: ap-chuncheon-1

jwt:
  secret-key:

siksha:
  oauth:
    google:
      client-id:
        android:
        ios-prod:
        ios-dev:
        web-prod:
        web-dev:
    kakao:
      app-id:
    apple:
      approved-audience:

slack:
  channel:
  token:
