name: Deploy-dev-siksha

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      ocir_repository: siksha-dev/siksha-spring-server
      dockerfile: Dockerfile
      profile: dev
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
