name: Manual Deployment to OCIR dev

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      ocir_repository: siksha-dev/siksha-spring-server
      dockerfile: Dockerfile
      profile: dev
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
