name: Deploy-prod-siksha

on:
  push:
    branches:
      - prd

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-siksha.yml
    with:
      ocir_repository: siksha-prod/siksha-spring-server
      dockerfile: Dockerfile
      profile: prod
    secrets:
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
